package com.itson.src.presentacion;

import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

public class RegistrarMetodoPago extends javax.swing.JFrame {

    private String metodoPago;

    public RegistrarMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;

        setTitle("Registrar Método de Pago");
        setSize(1440, 720);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JLabel titulo = new JLabel("Pago con " + metodoPago, SwingConstants.CENTER);
        panel.add(titulo, BorderLayout.NORTH);

        JPanel centro = new JPanel();
        centro.setLayout(new BoxLayout(centro, BoxLayout.Y_AXIS));

        if (metodoPago.equalsIgnoreCase("Efectivo")) {
            centro.add(new JLabel("Pagarás en efectivo al recibir el pedido."));
        } else if (metodoPago.equalsIgnoreCase("Tarjeta de crédito")
                || metodoPago.equalsIgnoreCase("Tarjeta de débito")) {

            centro.add(new JLabel("Número de tarjeta:"));
            JTextField txtNumeroTarjeta = new JTextField();
            centro.add(txtNumeroTarjeta);

            centro.add(new JLabel("Nombre en la tarjeta:"));
            JTextField txtNombreTarjeta = new JTextField();
            centro.add(txtNombreTarjeta);

            centro.add(new JLabel("Fecha de expiración (MM/AA):"));
            JTextField txtExpiracion = new JTextField();
            centro.add(txtExpiracion);

            centro.add(new JLabel("CVV:"));
            JTextField txtCVV = new JTextField();
            centro.add(txtCVV);

        } else if (metodoPago.equalsIgnoreCase("Transferencia bancaria")
                || metodoPago.equalsIgnoreCase("PayPal")
                || metodoPago.equalsIgnoreCase("Mercado Pago")) {

            centro.add(new JLabel("Se te redirigirá a la plataforma de pago: " + metodoPago));
        }

        panel.add(centro, BorderLayout.CENTER);

        JButton btnConfirmar = new JButton("Confirmar Pago");
        btnConfirmar.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Pago registrado con éxito usando: " + metodoPago);
            dispose();
        });

        panel.add(btnConfirmar, BorderLayout.SOUTH);

        add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
